version: configuring.{build}
configuration:
- Debug
- Release
platform:
- Win32
- x64
clone_folder: c:\SLBuild\cabl
init:
- cmd: choco install doxygen.install
- cmd: >-
    cd c:\SLBuild\

    nuget install boost_python-vc140 -Version 1.62.0

    cd cabl

environment:
  CABL_ROOT: c:\SLBuild\cabl
  BOOST_INCLUDEDIR: C:\SLBuild\boost.1.62.0.0\lib\native\include
  BOOST_PYTHON_ROOT: C:\SLBuild\boost_python-vc140.1.62.0.0\lib\native
  PYTHON_VERSION: 27
  TEST_JUNIT: ON
  TEST_ALL: ON
  STATIC_LIBS: ON
  SHARED_LIBS: ON
  FORCE_BUILD_DEPENDENCIES: ON

install:
  - git submodule update --init --recursive

build_script:
- cmd: >-
    echo Running cmake...

    echo Building %CONFIGURATION% - %PLATFORM%

    c:

    cd %CABL_ROOT%

    mkdir build-%PLATFORM%

    pushd build-%PLATFORM%

    if %PLATFORM% == x64 (set GENERATOR="Visual Studio 14 2015 Win64") else (set GENERATOR="Visual Studio 14 2015")

    if %PLATFORM% == x64 (set BOOST_LIBRARYDIR=%BOOST_PYTHON_ROOT%\address-model-64\lib) else (set BOOST_LIBRARYDIR=%BOOST_PYTHON_ROOT%\address-model-32\lib)

    if %PLATFORM% == x64 (set PYTHON_ROOT=c:\Python%PYTHON_VERSION%-x64) else (set PYTHON_ROOT=c:\Python%PYTHON_VERSION%)

    set BOOST_DEP=-DBOOST_INCLUDEDIR=%BOOST_INCLUDEDIR% -DBOOST_LIBRARYDIR=%BOOST_LIBRARYDIR%

    set PYTHON_DEP=-DPYTHON_LIBRARY=%PYTHON_ROOT%\libs\python%PYTHON_VERSION%.lib -DPYTHON_INCLUDE_DIR=%PYTHON_ROOT%\include

    mkdir nanomsg

    cd nanomsg

    set NN_BUILD_OPT=-DNN_STATIC_LIB=ON -DNN_ENABLE_DOC=OFF -DNN_TESTS=OFF -DNN_TOOLS=OFF -DNN_ENABLE_NANOCAT=OFF

    cmake -G %GENERATOR% %NN_BUILD_OPT% -DCMAKE_INSTALL_PREFIX:PATH=%CABL_ROOT%\build-%PLATFORM%\nanomsg %CABL_ROOT%\modules\nanomsg

    cd ..

    cmake --build %CABL_ROOT%\build-%PLATFORM%\nanomsg --target install --config %CONFIGURATION%

    set NANOMSG_DEP=-DNANOMSG_ROOT=%CABL_ROOT%\build-%PLATFORM%\nanomsg

    set ALL_DEP=%BOOST_DEP% %PYTHON_DEP% %NANOMSG_DEP%

    set CABL_OPTIONS=-DCABL_TEST_JUNIT=%TEST_JUNIT% -DCABL_TEST_ALL=%TEST_ALL% -DCABL_FORCE_BUILD_DEPENDENCIES=%FORCE_BUILD_DEPENDENCIES%

    set BUILD_OPTIONS=-DBUILD_STATIC_LIBS=%STATIC_LIBS% -DBUILD_SHARED_LIBS=%SHARED_LIBS%

    cmake -G %GENERATOR% -DCMAKE_BUILD_TYPE=%CONFIGURATION% %ALL_DEP% %CABL_OPTIONS% %BUILD_OPTIONS% ..

    cd ..

    cmake --build build-%PLATFORM% --config %CONFIGURATION%

    mkdir build-%PLATFORM%\%CONFIGURATION%\include

    xcopy inc build-%PLATFORM%\%CONFIGURATION%\include /e /y /I

    mkdir artifacts-%CONFIGURATION%

    cd build-%PLATFORM%\%CONFIGURATION%\

    del hidapi*.*;libusb*.*;rtmidi*.*

    if %CONFIGURATION% == Debug (copy %BOOST_LIBRARYDIR%\boost_python-vc140-mt-gd-*.dll ) else (copy %BOOST_LIBRARYDIR%\boost_python-vc140-mt-1*.dll )

    7z a -tzip cabl-win.zip -r *

    move /y *.zip ..\..\artifacts-%CONFIGURATION%

    cd ..\..\

after_build:
- cmd: >-
    cd %CABL_ROOT%\artifacts-%CONFIGURATION%

    if %PLATFORM% == x64 (echo Preparing to deploy cabl-win-64_%APPVEYOR_BUILD_VERSION%.zip) else (echo Preparing to deploy cabl-win-32_%APPVEYOR_BUILD_VERSION%.zip)

    if %PLATFORM% == x64 (ren cabl-win.zip cabl-win-64_%APPVEYOR_BUILD_VERSION%.zip) else (ren cabl-win.zip cabl-win-32_%APPVEYOR_BUILD_VERSION%.zip)

    cd ..

before_test:
- cmd: >-
    cd %CABL_ROOT%\

    cmake --build build-%PLATFORM% --config %CONFIGURATION% --target check

artifacts:
- path: artifacts-Release/cabl-win-32_*.zip
  name: cabl (32bit)
- path: artifacts-Release/cabl-win-64_*.zip
  name: cabl (64bit)

deploy:
- provider: Environment
  name: cabl-win-64
  on:
    branch: master
    CONFIGURATION: Release
    PLATFORM: x64

- provider: Environment
  name: cabl-win-32
  on:
    branch: master
    CONFIGURATION: Release
    PLATFORM: Win32

on_finish:
- ps: >-
    $testReportPath = "c:\SLBuild\cabl\build-$($env:PLATFORM)\test\$($env:CONFIGURATION)\test-report.junit.xml"

    if([System.IO.File]::Exists($testReportPath)){
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testReportPath))
    }
